# Generated by Django 4.2.7 on 2025-09-26 12:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('document_text', models.TextField()),
                ('overall_risk_score', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=10)),
                ('total_clauses', models.IntegerField()),
                ('high_risk_count', models.IntegerField()),
                ('medium_risk_count', models.IntegerField()),
                ('low_risk_count', models.IntegerField()),
                ('overview', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClauseAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_id', models.IntegerField()),
                ('original_text', models.TextField()),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=10)),
                ('summary', models.TextField()),
                ('legal_conflicts', models.JSONField(default=list)),
                ('explanation', models.TextField()),
                ('relevant_laws', models.JSONField(default=list)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='analyzer.analysissession')),
            ],
            options={
                'ordering': ['clause_id'],
            },
        ),
    ]
